# Generated by Django 3.2.4 on 2021-06-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('finances', models.FileField(upload_to='documents/', verbose_name='Finances Excel')),
                ('finance_data', models.JSONField(null=True)),
            ],
        ),
    ]
