# Generated by Django 5.0.7 on 2024-07-15 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_number", models.CharField(max_length=50)),
                ("legal_description", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=100)),
                ("first_owner", models.CharField(max_length=100)),
                ("use_code", models.CharField(max_length=50)),
                ("rating_category", models.CharField(max_length=50)),
                ("market_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "registered_extent",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("suburb", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_number", models.CharField(max_length=50)),
                ("erf_number", models.CharField(max_length=10)),
                ("government_code", models.CharField(max_length=50)),
                ("exemptions", models.CharField(max_length=50)),
                ("phasing_in", models.CharField(max_length=50)),
                ("sra_code", models.CharField(max_length=50)),
                ("deeds_township_farm", models.CharField(max_length=50)),
                ("rebates", models.CharField(max_length=50)),
                ("exclusions", models.CharField(max_length=50)),
                ("property_type", models.CharField(max_length=50)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="full_title_property.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
